Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.projectName}-${self:custom.stage}-${self:custom.serviceName}-UserPool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AutoVerifiedAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      UsernameAttributes:
        - email
      MfaConfiguration: OFF
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: False
          RequireUppercase: True
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: user_name
          Required: false
        - AttributeDataType: String
          Mutable: true
          Name: phone_number
          Required: false
      UsernameConfiguration:
        CaseSensitive: False

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: GoogleIdentityProvider
    Properties:
      ClientName: ${self:custom.projectName}-${self:custom.stage}-${self:custom.serviceName}-UserPoolClient
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - ${self:custom.signinCallback}
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      UserPoolId: !Ref UserPool
      SupportedIdentityProviders:
        - COGNITO
        - Google
      GenerateSecret: False
      RefreshTokenValidity: 180

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: ${self:custom.projectName}-${self:custom.stage}-${self:custom.serviceName}
      UserPoolId: !Ref UserPool

  UserPoolGroupAdministrator:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Administrator
      GroupName: admin
      Precedence: 0
      UserPoolId: !Ref UserPool

  UserPoolGroupPracticeManager:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Super Administrator
      GroupName: super_admin
      UserPoolId: !Ref UserPool

  GatewayResponse:
    Type: "AWS::ApiGateway::GatewayResponse"
    Properties:
      ResponseParameters:
        gatewayresponse.header.WWW-Authenticate: "'Basic'"
      ResponseType: UNAUTHORIZED
      RestApiId:
        Ref: "ApiGatewayRestApi"
      StatusCode: "401"

  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      ProviderName: Google
      ProviderType: Google
      UserPoolId: !Ref UserPool
      AttributeMapping:
        email: email
        given_name: given_name
        family_name: family_name
        picture: picture
        name: name
      ProviderDetails:
        client_id: "{{resolve:ssm:/gcp/google-oauth-client-id}}"
        client_secret: "{{resolve:ssm:/gcp/google-oauth-client-secret}}"
        authorize_scopes: "openid email profile phone"

  UserPoolIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /techtix/cognito-user-pool-id-${self:custom.stage}
      Type: String
      Value: !Ref UserPool
      Description: Cognito User Pool ID for ${self:custom.stage} stage

  UserPoolClientIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /techtix/cognito-app-client-id-${self:custom.stage}
      Type: String
      Value: !Ref UserPoolClient
      Description: Cognito User Pool Client ID for ${self:custom.stage} stage

  CognitoDomainUrlSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /techtix/cognito-domain-url-${self:custom.stage}
      Type: String
      Value: !Sub "https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
      Description: Cognito User Pool Domain URL for ${self:custom.stage} stage

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: UserPoolId-${self:custom.stage}

  AppClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: AppClientId-${self:custom.stage}

  UserPoolDomainUrl:
    Value: !Sub "https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
    Export:
      Name: UserPoolDomainUrl-${self:custom.stage}

  BasicAuthAuthorizerARN:
    Value:
      Fn::GetAtt:
        - BasicAuthAuthorizerLambdaFunction
        - Arn
    Export:
      Name: BasicAuthAuthorizerARN-${self:custom.stage}
